name: weather_app
description: "Aplicación Flutter para prueba técnica - Clima y Eventos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  realm: ^20.1.1
  path_provider: ^2.0.14
  flutter_flavorizr: ^2.3.1 
  go_router: ^14.6.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/dev.png
    - assets/icons/prod.png

flavorizr:
  app:
    android:
      flavorDimensions: "env"
    ios:
      bundleId: "com.weather.weatherapp"
  flavors:
    dev:
      app:
        name: "WeatherApp Dev"
        icon: "assets/icons/dev.png"
    prod:
      app:
        name: "WeatherApp"
        icon: "assets/icons/prod.png"

